name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for helping out the development of this project by placing your first issue. The team behind nwa will address its issues as soon as possible. Best regards, the developers.'
        pr-message: 'Thank you for committing your first pull request and helping out the development of this project. Requests will be examined as soon as possible. We hope you will stay connected and keep contributing. Best regards, your fellow contributers.'
